name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: 
          echo "Hellow World!!"
          echo "Hellow NewtonInfo!!"
      - name: Print goodbye
        run: echo "Done--bye"    
  
